/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <vector>
#include <opencv2\core\core.hpp>
#include <opencv2\highgui\highgui.hpp>
#include <opencv2\imgproc\imgproc.hpp>
using namespace cv;
/* Header for class com_example_imageprocess_ImageProcess */

#ifndef _Included_com_example_imageprocess_ImageProcess
#define _Included_com_example_imageprocess_ImageProcess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_imageprocess_ImageProcess
 * Method:    nativeFindRegions
 * Signature: (JJLjava/util/ArrayList;)V
 */
JNIEXPORT void JNICALL Java_com_example_imageprocess_ImageProcess_nativeFindRegions
  (JNIEnv *, jobject, jlong, jlong, jobject);

/*
 * Class:     com_example_imageprocess_ImageProcess
 * Method:    nativeRoi
 * Signature: (JJIIII)V
 */
JNIEXPORT void JNICALL Java_com_example_imageprocess_ImageProcess_nativeRoi
  (JNIEnv *, jobject, jlong, jlong, jint, jint, jint, jint);

/*
 * Class:     com_example_imageprocess_ImageProcess
 * Method:    nativeMatch
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_example_imageprocess_ImageProcess_nativeMatch
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
